param(
    [Parameter(Position = 0)]
    [string]$Tool,
    [Parameter(Position = 1, ValueFromRemainingArguments)]
    [string[]]$ExtraArgs
)

$UpdateTools = @(
    @{ Key = "claude"; Label = "Claude Code" },
    @{ Key = "gh_cli"; Label = "GitHub CLI (Copilot dependency)" },
    @{ Key = "copilot"; Label = "GitHub Copilot CLI" },
    @{ Key = "gemini"; Label = "Gemini CLI" },
    @{ Key = "codex"; Label = "Codex CLI" },
    @{ Key = "pi"; Label = "Pi Coding Agent" },
    @{ Key = "pi_vs_claude_code"; Label = "Pi vs Claude Code" },
    @{ Key = "opencode"; Label = "OpenCode" },
    @{ Key = "hermes"; Label = "Hermes Agent" }
)

$UsageTools = @(
    @{ Key = "claude"; Label = "Claude Code" },
    @{ Key = "codex"; Label = "Codex CLI" },
    @{ Key = "gemini"; Label = "Gemini CLI" },
    @{ Key = "copilot"; Label = "GitHub Copilot CLI" }
)

function Get-AiCliConfigPath {
    if ($env:AI_CLI_CONFIG) { return $env:AI_CLI_CONFIG }
    if ($env:XDG_CONFIG_HOME) { return (Join-Path $env:XDG_CONFIG_HOME "ai-cli/config") }
    return (Join-Path $HOME ".config/ai-cli/config")
}

function Get-AiCliDataDir {
    if ($env:XDG_DATA_HOME) { return (Join-Path $env:XDG_DATA_HOME "ai-cli") }
    if ($env:LOCALAPPDATA) { return (Join-Path $env:LOCALAPPDATA "ai-cli") }
    return (Join-Path $HOME ".local/share/ai-cli")
}

function Get-AiCliConfigKey($Category, $ToolName) {
    return ("{0}_{1}" -f $Category, $ToolName).ToUpperInvariant()
}

function Get-AiCliConfig {
    $path = Get-AiCliConfigPath
    $config = @{}
    if (-not (Test-Path $path)) { return $config }

    foreach ($line in Get-Content $path) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) { continue }
        $idx = $trimmed.IndexOf("=")
        if ($idx -le 0) { continue }
        $key = $trimmed.Substring(0, $idx)
        $value = $trimmed.Substring($idx + 1)
        $config[$key] = $value
    }
    return $config
}

function Test-AiCliEnabled($Category, $ToolName) {
    $config = Get-AiCliConfig
    $key = Get-AiCliConfigKey $Category $ToolName
    $value = if ($config.ContainsKey($key)) { "$($config[$key])".ToLowerInvariant() } else { "1" }

    switch ($value) {
        { $_ -in @("1", "true", "yes", "y", "on") } { return $true }
        { $_ -in @("0", "false", "no", "n", "off") } { return $false }
        default { return $true }
    }
}

function Read-AiCliYesNo($Label, $Current) {
    $suffix = if ($Current) { "[Y/n]" } else { "[y/N]" }
    while ($true) {
        $answer = Read-Host ("  {0,-34} {1}" -f $Label, $suffix)
        switch -Regex ($answer) {
            "^\s*$" { return [bool]$Current }
            "^(y|yes)$" { return $true }
            "^(n|no)$" { return $false }
            default { Write-Host "Please answer yes or no." -ForegroundColor Yellow }
        }
    }
}

function Invoke-AiCliSetup {
    $path = Get-AiCliConfigPath
    $lines = @(
        "# ai-cli configuration",
        "# Generated by: ai setup",
        ""
    )

    Write-Host "ai-cli setup" -ForegroundColor Cyan
    Write-Host "Choose which tools ai-cli should install or update by default."
    Write-Host "Config: $path"
    Write-Host ""

    Write-Host "Tools installed or updated by 'ai update':" -ForegroundColor Cyan
    foreach ($toolInfo in $UpdateTools) {
        $toolKey = $toolInfo["Key"]
        $toolLabel = $toolInfo["Label"]
        $key = Get-AiCliConfigKey "update" $toolKey
        $enabled = Read-AiCliYesNo $toolLabel (Test-AiCliEnabled "update" $toolKey)
        $enabledValue = if ($enabled) { 1 } else { 0 }
        $lines += ("{0}={1}" -f $key, $enabledValue)
    }

    $lines += ""
    Write-Host ""
    Write-Host "Usage checks used by 'ai usage':" -ForegroundColor Cyan
    foreach ($toolInfo in $UsageTools) {
        $toolKey = $toolInfo["Key"]
        $toolLabel = $toolInfo["Label"]
        $key = Get-AiCliConfigKey "usage" $toolKey
        $enabled = Read-AiCliYesNo $toolLabel (Test-AiCliEnabled "usage" $toolKey)
        $enabledValue = if ($enabled) { 1 } else { 0 }
        $lines += ("{0}={1}" -f $key, $enabledValue)
    }

    $dir = Split-Path -Parent $path
    if ($dir) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $lines | Set-Content -Path $path -Encoding UTF8
    Write-Host ""
    Write-Host "Saved setup to $path" -ForegroundColor Green
}

function Get-WingetVersion($PackageId) {
    $lines = winget list --id $PackageId --disable-interactivity 2>$null
    foreach ($line in $lines) {
        if ($line -match $PackageId) {
            if ($line -match '(\d+\.\d+[\.\d]*)') { return $Matches[1] }
        }
    }
    return $null
}

function Update-WingetPackage($DisplayName, $PackageId) {
    Write-Host "==> Checking $DisplayName..." -ForegroundColor Cyan
    $ver = Get-WingetVersion $PackageId
    if (-not $ver) {
        Write-Host "  Not installed" -ForegroundColor Yellow
        return
    }
    $output = winget upgrade $PackageId --disable-interactivity 2>&1 | Out-String
    if ($output -match "No available upgrade found|No newer package") {
        Write-Host "  Already up to date ($ver)" -ForegroundColor Green
    } else {
        $newVer = Get-WingetVersion $PackageId
        if ($newVer) {
            Write-Host "  Updated $ver -> $newVer" -ForegroundColor Yellow
        } else {
            Write-Host "  Updated successfully" -ForegroundColor Yellow
        }
    }
}

function Update-GhCopilot {
    Write-Host "==> Checking GitHub Copilot CLI..." -ForegroundColor Cyan
    $output = gh copilot update 2>&1 | Out-String
    if ($output -match "No update needed.*current version is ([^\s,]+)") {
        Write-Host "  Already up to date ($($Matches[1]))" -ForegroundColor Green
    } elseif ($output -match "Updated|updated|Updating") {
        Write-Host "  Updated successfully" -ForegroundColor Yellow
    } else {
        Write-Host "  Already up to date" -ForegroundColor Green
    }
}

function Update-NpmPackage($DisplayName, $Package) {
    Write-Host "==> Checking $DisplayName..." -ForegroundColor Cyan
    $current = (npm list -g $Package --depth=0 --json 2>$null | ConvertFrom-Json).dependencies.$Package.version
    $latest  = (npm view $Package version 2>$null).Trim()
    if (-not $current) {
        Write-Host "  Not installed, installing $latest..." -ForegroundColor Yellow
        npm install -g "${Package}@latest" --loglevel error
    } elseif ($current -eq $latest) {
        Write-Host "  Already up to date ($current)" -ForegroundColor Green
    } else {
        Write-Host "  Updating $current -> $latest..." -ForegroundColor Yellow
        npm install -g "${Package}@latest" --loglevel error
    }
}

function Get-PiVsClaudeCodeDir {
    if ($env:AI_CLI_PI_VS_CLAUDE_CODE_DIR) { return $env:AI_CLI_PI_VS_CLAUDE_CODE_DIR }
    return (Join-Path (Get-AiCliDataDir) "pi-vs-claude-code")
}

function Get-GitHead($RepoDir) {
    $head = git -C $RepoDir rev-parse --short HEAD 2>$null
    if ($LASTEXITCODE -eq 0) { return (($head | Select-Object -First 1) -as [string]) }
    return $null
}

function Update-PiVsClaudeCode {
    Write-Host "==> Checking Pi vs Claude Code..." -ForegroundColor Cyan

    $repoUrl = "https://github.com/disler/pi-vs-claude-code.git"
    $repoDir = Get-PiVsClaudeCodeDir
    $gitDir = Join-Path $repoDir ".git"

    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Write-Host "  Git is required to install this repo." -ForegroundColor Yellow
        return
    }

    if (Test-Path $gitDir) {
        $current = Get-GitHead $repoDir
        git -C $repoDir pull --ff-only *> $null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  Update failed. Run git pull manually in $repoDir for details." -ForegroundColor Yellow
            return
        }

        $updated = Get-GitHead $repoDir
        if ($current -and $current -eq $updated) {
            Write-Host "  Repo already up to date ($updated)" -ForegroundColor Green
        } else {
            $displayCurrent = if ($current) { $current } else { "unknown" }
            $displayUpdated = if ($updated) { $updated } else { "unknown" }
            Write-Host "  Updated repo $displayCurrent -> $displayUpdated" -ForegroundColor Yellow
        }
    } elseif (Test-Path $repoDir) {
        Write-Host "  $repoDir exists but is not a git checkout. Set AI_CLI_PI_VS_CLAUDE_CODE_DIR to another path." -ForegroundColor Yellow
        return
    } else {
        $parent = Split-Path -Parent $repoDir
        if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
        Write-Host "  Not installed, cloning..." -ForegroundColor Yellow
        git clone $repoUrl $repoDir *> $null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  Clone failed. Run git clone manually for details." -ForegroundColor Yellow
            return
        }
        Write-Host "  Cloned to $repoDir" -ForegroundColor Green
    }

    if (-not (Get-Command bun -ErrorAction SilentlyContinue)) {
        Write-Host "  Bun is required for dependencies. Install Bun, then rerun 'ai update'." -ForegroundColor Yellow
        return
    }

    bun install --cwd $repoDir *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Dependency install failed. Run 'bun install --cwd `"$repoDir`"' for details." -ForegroundColor Yellow
        return
    }

    if (Get-Command just -ErrorAction SilentlyContinue) {
        Write-Host "  Dependencies installed. Run recipes from $repoDir with 'just'." -ForegroundColor Green
    } else {
        Write-Host "  Dependencies installed. Install 'just' to use the bundled recipes in $repoDir." -ForegroundColor Yellow
    }
}

function Add-HermesPathForCurrentSession {
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA "hermes\hermes-agent\venv\Scripts"),
        (Join-Path $env:LOCALAPPDATA "hermes\hermes-agent")
    )
    $pathItems = $env:Path -split ";"

    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path $candidate) -and ($pathItems -notcontains $candidate)) {
            $env:Path = "$candidate;$env:Path"
            $pathItems = $env:Path -split ";"
        }
    }
}

function Get-HermesVersion {
    if (-not (Get-Command hermes -ErrorAction SilentlyContinue)) {
        return $null
    }

    $verOutput = hermes --version 2>$null | Select-Object -First 1
    if (-not $verOutput) {
        $verOutput = hermes version 2>$null | Select-Object -First 1
    }
    if ($verOutput -match 'v?(\d+\.\d+\.\d+)') {
        return $Matches[1]
    }
    return $null
}

function Install-Hermes {
    $installUrl = "https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.ps1"

    try {
        $installer = Invoke-RestMethod -Uri $installUrl -UseBasicParsing
        $scriptBlock = [scriptblock]::Create($installer)
        & $scriptBlock -SkipSetup -NonInteractive
    } catch {
        Write-Host "  Installation failed: $_" -ForegroundColor Yellow
        return $false
    }

    Add-HermesPathForCurrentSession
    return $true
}

function Update-Hermes {
    Write-Host "==> Checking Hermes Agent..." -ForegroundColor Cyan
    if (-not (Get-Command hermes -ErrorAction SilentlyContinue)) {
        Write-Host "  Not installed, installing..." -ForegroundColor Yellow
        if (-not (Install-Hermes)) {
            return
        }

        if (-not (Get-Command hermes -ErrorAction SilentlyContinue)) {
            Write-Host "  Installed, but hermes is not on PATH yet. Restart your shell and try again." -ForegroundColor Yellow
            return
        }

        $installed = Get-HermesVersion
        if ($installed) {
            Write-Host "  Installed ($installed)" -ForegroundColor Green
        } else {
            Write-Host "  Installed" -ForegroundColor Green
        }
        return
    }

    $current = Get-HermesVersion

    $hadCi = Test-Path Env:CI
    $previousCi = $env:CI
    try {
        # Hermes updates reinstall Node dependencies whose postinstall hooks may
        # print cosmetic demos directly to the terminal. CI=true suppresses
        # those demos without disabling required install scripts.
        if (-not $env:CI) { $env:CI = "true" }
        hermes update >$null 2>&1
    } finally {
        if ($hadCi) {
            $env:CI = $previousCi
        } else {
            Remove-Item Env:CI -ErrorAction SilentlyContinue
        }
    }

    $newVer = Get-HermesVersion

    if ($current -and $current -eq $newVer) {
        Write-Host "  Already up to date ($current)" -ForegroundColor Green
    } elseif ($newVer) {
        $displayCurrent = if ($current) { $current } else { "unknown" }
        Write-Host "  Updated $displayCurrent -> $newVer" -ForegroundColor Yellow
    } else {
        Write-Host "  Update check complete" -ForegroundColor Green
    }
}

switch ($Tool) {
    "claude"  { claude --dangerously-skip-permissions @ExtraArgs }
    "codex"   { codex --yolo @ExtraArgs }
    "gemini"  { gemini --yolo @ExtraArgs }
    "copilot" { gh copilot --yolo @ExtraArgs }
    "pi"      { pi @ExtraArgs }
    "hermes"  { hermes --yolo @ExtraArgs }
    "update"  {
        $ran = $false
        if (Test-AiCliEnabled "update" "claude") {
            if ($ran) { Write-Host "" }
            Update-WingetPackage "Claude Code" "Anthropic.ClaudeCode"
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "gh_cli") {
            if ($ran) { Write-Host "" }
            Update-WingetPackage "GitHub CLI" "GitHub.cli"
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "copilot") {
            if ($ran) { Write-Host "" }
            Update-GhCopilot
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "gemini") {
            if ($ran) { Write-Host "" }
            Update-NpmPackage "Gemini CLI" "@google/gemini-cli"
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "codex") {
            if ($ran) { Write-Host "" }
            Update-NpmPackage "Codex CLI" "@openai/codex"
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "pi") {
            if ($ran) { Write-Host "" }
            Update-NpmPackage "Pi Coding Agent" "@earendil-works/pi-coding-agent"
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "pi_vs_claude_code") {
            if ($ran) { Write-Host "" }
            Update-PiVsClaudeCode
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "opencode") {
            if ($ran) { Write-Host "" }
            Update-NpmPackage "OpenCode" "opencode-ai"
            $ran = $true
        }
        if (Test-AiCliEnabled "update" "hermes") {
            if ($ran) { Write-Host "" }
            Update-Hermes
            $ran = $true
        }
        if ($ran) {
            Write-Host ""
            Write-Host "All selected AI tools checked." -ForegroundColor Green
        } else {
            Write-Host "No update tools selected. Run 'ai setup' to choose tools." -ForegroundColor Yellow
        }
    }
    "setup" { Invoke-AiCliSetup }
    default {
        Write-Host "Usage: ai <tool> [extra args]"
        Write-Host "  ai claude   -> claude --dangerously-skip-permissions"
        Write-Host "  ai codex    -> codex --yolo"
        Write-Host "  ai gemini   -> gemini --yolo"
        Write-Host "  ai copilot  -> gh copilot --yolo"
        Write-Host "  ai pi       -> pi"
        Write-Host "  ai hermes   -> hermes --yolo"
        Write-Host "  ai update   -> update all AI tools"
        Write-Host "  ai setup    -> choose tools for update and usage checks"
    }
}
