#!/usr/bin/env bash
set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

VERBOSE=false
for arg in "$@"; do
    if [[ "$arg" == "--verbose" || "$arg" == "-v" ]]; then
        VERBOSE=true
    fi
done
# Strip --verbose / -v from args
args=()
for arg in "$@"; do
    [[ "$arg" == "--verbose" || "$arg" == "-v" ]] || args+=("$arg")
done
set -- "${args[@]+"${args[@]}"}"

path_has_dir() {
    local dir="$1"
    case ":$PATH:" in
        *":$dir:"*) return 0 ;;
        *) return 1 ;;
    esac
}

prepend_path_dir() {
    local dir="$1"
    local item new_path old_ifs

    [[ -d "$dir" ]] || return 0
    new_path="$dir"
    old_ifs="$IFS"
    IFS=:
    for item in ${PATH:-}; do
        [[ -n "$item" && "$item" != "$dir" ]] || continue
        new_path="${new_path}:$item"
    done
    IFS="$old_ifs"
    PATH="$new_path"
}

npm_config_prefix() {
    npm config get prefix 2>/dev/null | head -n 1 || true
}

npm_prefix_is_under_home() {
    local prefix="$1"
    [[ -n "$prefix" && "$prefix" == "$HOME"/* ]]
}

npm_user_prefix() {
    if [[ -n "${AI_CLI_NPM_PREFIX:-}" ]]; then
        printf '%s\n' "$AI_CLI_NPM_PREFIX"
        return
    fi

    local configured_prefix
    configured_prefix="$(npm_config_prefix)"
    if npm_prefix_is_under_home "$configured_prefix"; then
        printf '%s\n' "$configured_prefix"
    else
        printf '%s\n' "$HOME/.local"
    fi
}

npm_user_bin() {
    printf '%s/bin\n' "$(npm_user_prefix)"
}

prepend_path_dir "$(npm_user_bin)"

AI_CLI_UPDATE_TOOLS=(claude gh_cli copilot antigravity codex pi pi_vs_claude_code hermes omx)
AI_CLI_USAGE_TOOLS=(claude codex antigravity copilot)

ai_cli_data_dir() {
    if [[ -n "${XDG_DATA_HOME:-}" ]]; then
        printf '%s/ai-cli\n' "$XDG_DATA_HOME"
    else
        printf '%s/.local/share/ai-cli\n' "$HOME"
    fi
}

ai_cli_config_file() {
    if [[ -n "${AI_CLI_CONFIG:-}" ]]; then
        printf '%s\n' "$AI_CLI_CONFIG"
    elif [[ -n "${XDG_CONFIG_HOME:-}" ]]; then
        printf '%s/ai-cli/config\n' "$XDG_CONFIG_HOME"
    else
        printf '%s/.config/ai-cli/config\n' "$HOME"
    fi
}

ai_cli_config_key() {
    local category="$1"
    local tool="$2"

    printf '%s_%s\n' \
        "$(printf '%s' "$category" | tr '[:lower:]' '[:upper:]')" \
        "$(printf '%s' "$tool" | tr '[:lower:]' '[:upper:]')"
}

ai_cli_config_get() {
    local key="$1"
    local default_value="${2:-1}"
    local config value

    config="$(ai_cli_config_file)"
    if [[ -f "$config" ]]; then
        value=$(awk -F= -v key="$key" '
            $1 == key {
                value = $0
                sub(/^[^=]*=/, "", value)
            }
            END {
                if (value != "") {
                    print value
                }
            }
        ' "$config")
        if [[ -n "$value" ]]; then
            printf '%s\n' "$value"
            return
        fi
    fi

    printf '%s\n' "$default_value"
}

ai_cli_enabled() {
    local category="$1"
    local tool="$2"
    local value

    value=$(ai_cli_config_get "$(ai_cli_config_key "$category" "$tool")" "1")
    value=$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')

    case "$value" in
        1|true|yes|y|on) return 0 ;;
        0|false|no|n|off) return 1 ;;
        *) return 0 ;;
    esac
}

ai_cli_tool_label() {
    case "$1" in
        claude)  printf 'Claude Code' ;;
        gh_cli)  printf 'GitHub CLI (Copilot dependency)' ;;
        copilot) printf 'GitHub Copilot CLI' ;;
        antigravity) printf 'Antigravity CLI' ;;
        codex)   printf 'Codex CLI' ;;
        pi)      printf 'Pi Coding Agent' ;;
        pi_vs_claude_code) printf 'Pi vs Claude Code' ;;
        hermes)  printf 'Hermes Agent' ;;
        omx)     printf 'Oh My Codex' ;;
        *)       printf '%s' "$1" ;;
    esac
}

prompt_yes_no() {
    local label="$1"
    local current="$2"
    local prompt answer

    if [[ "$current" == "1" ]]; then
        prompt="[Y/n]"
    else
        prompt="[y/N]"
    fi

    while true; do
        printf '  %-34s %s ' "$label" "$prompt"
        IFS= read -r answer || answer=""
        case "$answer" in
            "")
                [[ "$current" == "1" ]]
                return
                ;;
            [Yy]|[Yy][Ee][Ss])
                return 0
                ;;
            [Nn]|[Nn][Oo])
                return 1
                ;;
            *)
                echo "Please answer yes or no."
                ;;
        esac
    done
}

do_setup() {
    local config tmp tool key current enabled
    local -a lines=()

    config="$(ai_cli_config_file)"

    echo -e "${CYAN}ai-cli setup${NC}"
    echo "Choose which tools ai-cli should install or update by default."
    echo "Config: $config"
    echo ""

    lines+=("# ai-cli configuration")
    lines+=("# Generated by: ai setup")
    lines+=("")

    echo -e "${CYAN}Tools installed or updated by 'ai update':${NC}"
    for tool in "${AI_CLI_UPDATE_TOOLS[@]}"; do
        key="$(ai_cli_config_key update "$tool")"
        if ai_cli_enabled update "$tool"; then
            current=1
        else
            current=0
        fi
        if prompt_yes_no "$(ai_cli_tool_label "$tool")" "$current"; then
            enabled=1
        else
            enabled=0
        fi
        lines+=("${key}=${enabled}")
    done

    lines+=("")
    echo ""
    echo -e "${CYAN}Usage checks used by 'ai usage':${NC}"
    for tool in "${AI_CLI_USAGE_TOOLS[@]}"; do
        key="$(ai_cli_config_key usage "$tool")"
        if ai_cli_enabled usage "$tool"; then
            current=1
        else
            current=0
        fi
        if prompt_yes_no "$(ai_cli_tool_label "$tool")" "$current"; then
            enabled=1
        else
            enabled=0
        fi
        lines+=("${key}=${enabled}")
    done

    mkdir -p "$(dirname "$config")"
    tmp="${config}.tmp.$$"
    {
        for line in "${lines[@]}"; do
            printf '%s\n' "$line"
        done
    } > "$tmp"
    mv "$tmp" "$config"

    echo ""
    echo -e "${GREEN}Saved setup to $config${NC}"
}

ensure_managed_block_in_file() {
    local file="$1"
    local block="$2"
    local dir

    dir="$(dirname "$file")"
    mkdir -p "$dir"
    touch "$file"
    python3 - "$file" "$block" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
block = sys.argv[2]
start = "# >>> ai-cli PATH >>>"
end = "# <<< ai-cli PATH <<<"
managed = f"{start}\n{block}\n{end}\n"

content = path.read_text() if path.exists() else ""
normalized = content.rstrip("\n")

if start in content and end in content:
    prefix, remainder = content.split(start, 1)
    _, suffix = remainder.split(end, 1)
    replacement = prefix.rstrip("\n")
    if replacement:
        replacement += "\n\n"
    replacement += managed
    suffix = suffix.lstrip("\n")
    if suffix:
        replacement += "\n" + suffix
    updated = replacement
else:
    updated = normalized
    if updated:
        updated += "\n\n"
    updated += managed

if not updated.endswith("\n"):
    updated += "\n"

changed = updated != content
path.write_text(updated)
sys.exit(0 if changed else 1)
PY
}

persist_user_bin_path() {
    local bin_dir shell_name block
    local -a files=()
    local updated=false

    bin_dir="$(npm_user_bin)"
    block="export PATH=\"$bin_dir:\$PATH\""
    shell_name="$(basename "${SHELL:-}")"

    case "$shell_name" in
        bash)
            files+=("$HOME/.bashrc" "$HOME/.profile")
            ;;
        zsh)
            files+=("$HOME/.zshrc" "$HOME/.zprofile")
            ;;
        fish)
            ensure_managed_block_in_file "$HOME/.config/fish/config.fish" "fish_add_path \"$bin_dir\"" && updated=true
            ;;
    esac

    files+=("$HOME/.profile")

    local file
    for file in "${files[@]}"; do
        ensure_managed_block_in_file "$file" "$block" && updated=true
    done

    $updated
}

read_npm_package_version() {
    local package="$1"
    local prefix="${2:-}"
    local -a cmd=(npm list -g "$package" --depth=0 --json)
    if [[ -n "$prefix" ]]; then
        cmd+=(--prefix "$prefix")
    fi
    "${cmd[@]}" 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('dependencies',{}).get('$package',{}).get('version',''))" 2>/dev/null || true
}

read_command_version() {
    local binary="$1"
    local output version

    if ! command -v "$binary" >/dev/null 2>&1; then
        return 1
    fi

    output=$("$binary" --version 2>/dev/null || "$binary" -v 2>/dev/null || true)
    version=$(printf '%s\n' "$output" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
    [[ -n "$version" ]] || return 1
    printf '%s\n' "$version"
}

npm_global_install_is_writable() {
    local prefix global_root

    prefix="$(npm_config_prefix)"
    [[ -n "$prefix" ]] || return 1

    global_root="$prefix/lib/node_modules"
    if [[ -d "$global_root" ]]; then
        [[ -w "$global_root" ]]
    else
        [[ -d "$prefix" && -w "$prefix" ]]
    fi
}

npm_install_prefix() {
    local configured_prefix
    if [[ -n "${AI_CLI_NPM_PREFIX:-}" ]]; then
        printf '%s\n' "$AI_CLI_NPM_PREFIX"
        return
    fi

    configured_prefix="$(npm_config_prefix)"
    if npm_global_install_is_writable && [[ -n "$configured_prefix" ]]; then
        printf '%s\n' "$configured_prefix"
    else
        printf '%s\n' "$(npm_user_prefix)"
    fi
}

npm_known_user_prefixes() {
    local prefix
    for prefix in "$(npm_user_prefix)" "$(npm_config_prefix)" "$HOME/.local" "$HOME/.npm-global"; do
        [[ -n "$prefix" ]] || continue
        npm_prefix_is_under_home "$prefix" || continue
        printf '%s\n' "$prefix"
    done | python3 -c 'import os,sys; seen=set();
for line in sys.stdin:
    value=os.path.normpath(line.strip())
    if value and value not in seen:
        seen.add(value); print(value)'
}

persist_npm_bin_path_if_user_managed() {
    local prefix="$1"
    local bin_dir="$prefix/bin"

    npm_prefix_is_under_home "$prefix" || return 0
    persist_user_bin_path >/dev/null || true
    if ! path_has_dir "$bin_dir"; then
        echo -e "${GREEN}  Added ${bin_dir} to your shell PATH for future sessions.${NC}"
    fi
}

cleanup_duplicate_npm_package_prefixes() {
    local display_name="$1"
    local package="$2"
    local binary="$3"
    local target_prefix="$4"
    local prefix version

    target_prefix="$(python3 -c 'import os,sys; print(os.path.normpath(sys.argv[1]))' "$target_prefix")"
    while IFS= read -r prefix; do
        [[ -n "$prefix" && "$prefix" != "$target_prefix" ]] || continue
        version=$(read_npm_package_version "$package" "$prefix")
        [[ -n "$version" ]] || continue
        [[ -e "$prefix/bin/$binary" || -L "$prefix/bin/$binary" ]] || continue

        echo -e "${YELLOW}  Removing duplicate ${display_name} ${version} from $prefix to prevent PATH shadowing.${NC}"
        if $VERBOSE; then
            npm uninstall -g --prefix "$prefix" "$package" || true
        else
            npm uninstall -g --prefix "$prefix" "$package" --loglevel error >/dev/null 2>&1 || true
        fi
    done < <(npm_known_user_prefixes)
}

npm_prefixes_for_target() {
    local target_prefix="$1"

    {
        printf '%s\n' "$target_prefix"
        npm_config_prefix
        npm_known_user_prefixes
    } | python3 -c 'import os,sys; seen=set();
for line in sys.stdin:
    value=os.path.normpath(line.strip())
    if value and value not in seen:
        seen.add(value); print(value)'
}

npm_prefix_is_writable_for_uninstall() {
    local prefix="$1"
    local global_root="$prefix/lib/node_modules"
    local bin_dir="$prefix/bin"

    [[ -d "$global_root" && -w "$global_root" ]] || return 1
    [[ ! -d "$bin_dir" || -w "$bin_dir" ]]
}

prompt_for_sudo() {
    local action="$1"

    if ! command -v sudo >/dev/null 2>&1; then
        echo -e "${RED}  sudo is required to $action, but sudo was not found.${NC}"
        return 1
    fi

    echo -e "${YELLOW}  sudo is required to $action.${NC}"
    if [[ ! -t 0 ]]; then
        echo -e "${YELLOW}  Run this command from an interactive terminal to enter your sudo password.${NC}"
        return 1
    fi

    sudo -v
}

ai_cli_skip_dependency_install() {
    [[ "${AI_CLI_SKIP_DEPENDENCY_INSTALL:-0}" == "1" ]]
}

ai_cli_package_manager() {
    if command -v pacman >/dev/null 2>&1; then
        printf 'pacman\n'
    elif command -v apt-get >/dev/null 2>&1; then
        printf 'apt\n'
    elif command -v dnf >/dev/null 2>&1; then
        printf 'dnf\n'
    elif command -v brew >/dev/null 2>&1; then
        printf 'brew\n'
    else
        printf 'none\n'
    fi
}

ai_cli_packages_for_dependency() {
    local manager="$1"
    local dependency="$2"

    case "$manager:$dependency" in
        pacman:curl) printf 'curl\n' ;;
        pacman:git) printf 'git\n' ;;
        pacman:python3) printf 'python\n' ;;
        pacman:npm) printf 'nodejs\nnpm\n' ;;
        pacman:gh) printf 'github-cli\n' ;;
        pacman:unzip) printf 'unzip\n' ;;
        pacman:just) printf 'just\n' ;;
        apt:curl) printf 'curl\n' ;;
        apt:git) printf 'git\n' ;;
        apt:python3) printf 'python3\n' ;;
        apt:npm) printf 'nodejs\nnpm\n' ;;
        apt:gh) printf 'gh\n' ;;
        apt:unzip) printf 'unzip\n' ;;
        apt:just) printf 'just\n' ;;
        dnf:curl) printf 'curl\n' ;;
        dnf:git) printf 'git\n' ;;
        dnf:python3) printf 'python3\n' ;;
        dnf:npm) printf 'nodejs\nnpm\n' ;;
        dnf:gh) printf 'gh\n' ;;
        dnf:unzip) printf 'unzip\n' ;;
        dnf:just) printf 'just\n' ;;
        brew:curl) printf 'curl\n' ;;
        brew:git) printf 'git\n' ;;
        brew:python3) printf 'python\n' ;;
        brew:npm) printf 'node\n' ;;
        brew:gh) printf 'gh\n' ;;
        brew:unzip) printf 'unzip\n' ;;
        brew:just) printf 'just\n' ;;
        *) return 1 ;;
    esac
}

ai_cli_install_packages() {
    local manager="$1"
    shift
    local -a packages=("$@")

    [[ ${#packages[@]} -gt 0 ]] || return 0

    if ai_cli_skip_dependency_install; then
        echo -e "${YELLOW}  Dependency install skipped by AI_CLI_SKIP_DEPENDENCY_INSTALL=1.${NC}"
        return 1
    fi

    case "$manager" in
        pacman)
            prompt_for_sudo "install ${packages[*]}" || return 1
            if $VERBOSE; then
                sudo pacman -Sy --noconfirm --needed "${packages[@]}"
            else
                sudo pacman -Sy --noconfirm --needed "${packages[@]}" >/dev/null
            fi
            ;;
        apt)
            prompt_for_sudo "install ${packages[*]}" || return 1
            if $VERBOSE; then
                sudo apt-get update
                sudo apt-get install -y "${packages[@]}"
            else
                sudo apt-get update -qq >/dev/null
                sudo apt-get install -y -qq "${packages[@]}" >/dev/null
            fi
            ;;
        dnf)
            prompt_for_sudo "install ${packages[*]}" || return 1
            if $VERBOSE; then
                sudo dnf install -y "${packages[@]}"
            else
                sudo dnf install -y -q "${packages[@]}" >/dev/null
            fi
            ;;
        brew)
            if $VERBOSE; then
                brew install "${packages[@]}"
            else
                brew install "${packages[@]}" >/dev/null
            fi
            ;;
        *)
            echo -e "${YELLOW}  No supported package manager found for ${packages[*]}.${NC}"
            return 1
            ;;
    esac
}

ensure_dependency_package() {
    local dependency="$1"
    local display_name="$2"
    local manager
    local package packages_text
    local -a packages=()

    manager="$(ai_cli_package_manager)"
    if [[ "$manager" == "apt" && "$dependency" == "gh" ]]; then
        ensure_command_dependency curl curl "curl" || return 1
        if [[ ! -f /etc/apt/sources.list.d/github-cli.list || ! -f /usr/share/keyrings/githubcli-archive-keyring.gpg ]]; then
            prompt_for_sudo "configure the GitHub CLI apt repository" || return 1
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg >/dev/null 2>&1
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
                | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
        fi
    fi

    if ! packages_text=$(ai_cli_packages_for_dependency "$manager" "$dependency"); then
        echo -e "${YELLOW}  Could not map $display_name to a package for this system.${NC}"
        return 1
    fi
    while IFS= read -r package; do
        [[ -n "$package" ]] && packages+=("$package")
    done <<< "$packages_text"

    echo -e "${YELLOW}  $display_name is missing, installing...${NC}"
    ai_cli_install_packages "$manager" "${packages[@]}"
}

ensure_command_dependency() {
    local command_name="$1"
    local dependency="$2"
    local display_name="$3"

    if command -v "$command_name" >/dev/null 2>&1; then
        return 0
    fi

    ensure_dependency_package "$dependency" "$display_name" || return 1
    command -v "$command_name" >/dev/null 2>&1
}

ensure_bun_dependency() {
    prepend_path_dir "$HOME/.bun/bin"
    if command -v bun >/dev/null 2>&1; then
        return 0
    fi

    echo -e "${YELLOW}  Bun is missing, installing...${NC}"
    if ai_cli_skip_dependency_install; then
        echo -e "${YELLOW}  Dependency install skipped by AI_CLI_SKIP_DEPENDENCY_INSTALL=1.${NC}"
        return 1
    fi

    ensure_command_dependency curl curl "curl" || return 1
    if [[ "$(uname -s)" == Linux* ]]; then
        ensure_command_dependency unzip unzip "unzip" || return 1
    fi

    if $VERBOSE; then
        curl -fsSL https://bun.com/install | bash
    else
        curl -fsSL https://bun.com/install 2>/dev/null | bash >/dev/null
    fi

    prepend_path_dir "$HOME/.bun/bin"
    command -v bun >/dev/null 2>&1
}

ensure_just_dependency() {
    if command -v just >/dev/null 2>&1; then
        return 0
    fi

    if [[ "${AI_CLI_JUST_CHECKED:-0}" == "1" ]]; then
        return 0
    fi
    AI_CLI_JUST_CHECKED=1

    ensure_dependency_package just "just" || {
        echo -e "${YELLOW}  just is still missing; Pi vs Claude Code dependencies can install, but recipes will not run until just is installed.${NC}"
        return 0
    }

    if ! command -v just >/dev/null 2>&1; then
        echo -e "${YELLOW}  just is still missing; Pi vs Claude Code dependencies can install, but recipes will not run until just is installed.${NC}"
    fi
}

ensure_update_dependencies() {
    local failed=false
    local checked=false

    echo -e "${CYAN}==> Checking ai-cli dependencies...${NC}"

    ensure_command_dependency python3 python3 "Python 3" || failed=true

    if ai_cli_enabled update claude || ai_cli_enabled update antigravity || ai_cli_enabled update hermes || ai_cli_enabled update omx; then
        ensure_command_dependency curl curl "curl" || failed=true
        checked=true
    fi

    if ai_cli_enabled update pi_vs_claude_code || ai_cli_enabled update hermes; then
        ensure_command_dependency git git "Git" || failed=true
        checked=true
    fi

    if ai_cli_enabled update codex || ai_cli_enabled update pi || ai_cli_enabled update omx; then
        ensure_command_dependency npm npm "Node.js/npm" || failed=true
        checked=true
    fi

    if ai_cli_enabled update gh_cli || ai_cli_enabled update copilot; then
        ensure_command_dependency gh gh "GitHub CLI" || failed=true
        checked=true
    fi

    if ai_cli_enabled update pi_vs_claude_code; then
        ensure_bun_dependency || failed=true
        ensure_just_dependency || true
        checked=true
    fi

    if ! $failed; then
        if $checked; then
            echo -e "${GREEN}  Dependencies ready.${NC}"
        else
            echo -e "${GREEN}  No selected tools require dependency checks.${NC}"
        fi
    fi

    ! $failed
}

npm_uninstall_package_from_prefix() {
    local prefix="$1"
    local package="$2"
    local npm_bin
    local -a cmd

    npm_bin="$(command -v npm 2>/dev/null || true)"
    if [[ -z "$npm_bin" ]]; then
        echo -e "${RED}  npm is required to remove $package.${NC}"
        return 1
    fi

    cmd=("$npm_bin" uninstall -g --prefix "$prefix" "$package")
    if ! $VERBOSE; then
        cmd+=(--loglevel error)
    fi

    if npm_prefix_is_writable_for_uninstall "$prefix"; then
        if $VERBOSE; then
            "${cmd[@]}"
        else
            "${cmd[@]}" >/dev/null
        fi
        return
    fi

    if ! prompt_for_sudo "change npm packages in $prefix"; then
        return 1
    fi

    if $VERBOSE; then
        sudo "${cmd[@]}"
    else
        sudo "${cmd[@]}" >/dev/null
    fi
}

cleanup_legacy_npm_package_prefixes() {
    local display_name="$1"
    local package="$2"
    local binary="$3"
    local target_prefix="$4"
    shift 4
    local -a legacy_packages=("$@")
    local legacy_package prefix version

    [[ ${#legacy_packages[@]} -gt 0 ]] || return 0

    for legacy_package in "${legacy_packages[@]}"; do
        [[ -n "$legacy_package" && "$legacy_package" != "$package" ]] || continue
        while IFS= read -r prefix; do
            [[ -n "$prefix" ]] || continue
            version=$(read_npm_package_version "$legacy_package" "$prefix")
            [[ -n "$version" ]] || continue
            [[ -e "$prefix/bin/$binary" || -L "$prefix/bin/$binary" ]] || continue

            echo -e "${YELLOW}  Removing legacy ${display_name} ${version} from $prefix to free $binary.${NC}"
            if ! npm_uninstall_package_from_prefix "$prefix" "$legacy_package"; then
                return 1
            fi
        done < <(npm_prefixes_for_target "$target_prefix")
    done
}

ensure_npm_binary_path() {
    local display_name="$1"
    local package="$2"
    local binary="$3"
    local target_prefix="$4"
    local target_bin="$target_prefix/bin"
    local resolved=""

    mkdir -p "$target_bin"
    persist_npm_bin_path_if_user_managed "$target_prefix"
    prepend_path_dir "$target_bin"
    cleanup_duplicate_npm_package_prefixes "$display_name" "$package" "$binary" "$target_prefix"

    resolved=$(command -v "$binary" 2>/dev/null || true)
    if [[ -n "$resolved" && "$resolved" != "$target_bin/$binary" ]]; then
        echo -e "${YELLOW}  WARNING: $binary resolves to $resolved, not $target_bin/$binary.${NC}"
        echo -e "${YELLOW}  Check your PATH for another earlier install.${NC}"
    fi
}

install_npm_package() {
    local display_name="$1"
    local package="$2"
    local binary="$3"
    shift 3
    local -a legacy_packages=("$@")
    local target_prefix
    local -a cmd=(npm install -g "${package}@latest" --no-fund)

    target_prefix="$(npm_install_prefix)"
    if [[ "$(npm_config_prefix)" != "$target_prefix" ]]; then
        mkdir -p "$target_prefix"
        cmd+=(--prefix "$target_prefix")
    fi

    if ! $VERBOSE; then
        cmd+=(--loglevel error)
    fi

    cleanup_legacy_npm_package_prefixes "$display_name" "$package" "$binary" "$target_prefix" "${legacy_packages[@]}"
    "${cmd[@]}"
    ensure_npm_binary_path "$display_name" "$package" "$binary" "$target_prefix"
}

check_npm_package() {
    local display_name="$1"
    local package="$2"
    local binary="$3"
    shift 3
    local -a legacy_packages=("$@")

    echo -e "${CYAN}==> Checking ${display_name}...${NC}"
    local current latest target_prefix
    target_prefix="$(npm_install_prefix)"
    current=$(read_npm_package_version "$package")
    if [[ -z "$current" ]]; then
        current=$(read_npm_package_version "$package" "$target_prefix")
    fi
    if [[ -z "$current" ]]; then
        current=$(read_command_version "$binary" || true)
    fi
    latest=$(npm view "$package" version 2>/dev/null || true)

    if [[ -z "$current" ]]; then
        echo -e "${YELLOW}  Not installed, installing ${latest:-latest}...${NC}"
        install_npm_package "$display_name" "$package" "$binary" "${legacy_packages[@]}"
    elif [[ "$current" == "$latest" ]]; then
        echo -e "${GREEN}  Already up to date (${current})${NC}"
        cleanup_legacy_npm_package_prefixes "$display_name" "$package" "$binary" "$target_prefix" "${legacy_packages[@]}"
        ensure_npm_binary_path "$display_name" "$package" "$binary" "$target_prefix"
    else
        echo -e "${YELLOW}  Updating ${current} -> ${latest:-latest}...${NC}"
        install_npm_package "$display_name" "$package" "$binary" "${legacy_packages[@]}"
    fi
}

canonical_file_path() {
    local path="$1"
    local dir base

    [[ -n "$path" ]] || return 1
    if [[ "$path" == */* ]]; then
        dir="${path%/*}"
        base="${path##*/}"
        [[ -n "$dir" ]] || dir="/"
    else
        dir="."
        base="$path"
    fi

    (
        cd -P -- "$dir" >/dev/null 2>&1
        printf '%s/%s\n' "$PWD" "$base"
    )
}

current_script_path() {
    local source="${BASH_SOURCE[0]:-$0}"

    [[ -n "$source" ]] || return 1
    if [[ "$source" != /* ]]; then
        source="$PWD/$source"
    fi
    canonical_file_path "$source"
}

doctor_install_file() {
    local source="$1"
    local dest="$2"
    local mode="$3"
    local dest_dir parent
    local use_sudo=false

    dest_dir="$(dirname "$dest")"
    parent="$(dirname "$dest_dir")"

    if [[ ! -d "$dest_dir" ]]; then
        if [[ -w "$parent" ]]; then
            if ! mkdir -p "$dest_dir"; then
                return 1
            fi
        else
            use_sudo=true
        fi
    fi

    if [[ -d "$dest_dir" ]]; then
        if [[ ! -w "$dest_dir" || ( -e "$dest" && ! -w "$dest" ) ]]; then
            use_sudo=true
        fi
    fi

    if $use_sudo; then
        if ! prompt_for_sudo "update $dest"; then
            return 1
        fi
        if ! sudo mkdir -p "$dest_dir"; then
            return 1
        fi
        sudo install -m "$mode" "$source" "$dest"
    else
        install -m "$mode" "$source" "$dest"
    fi
}

doctor_check_ai_cli_install() {
    echo -e "${CYAN}==> Checking ai-cli launcher...${NC}"

    local source path_ai install_path
    source="$(current_script_path || true)"
    if [[ -z "$source" || ! -f "$source" ]]; then
        echo -e "${YELLOW}  Could not locate the running ai-cli script; skipping launcher repair.${NC}"
        return 0
    fi

    path_ai="$(command -v ai 2>/dev/null || true)"
    if [[ -z "$path_ai" ]]; then
        install_path="${AI_CLI_INSTALL_DIR:-/usr/local/bin}/ai"
        echo -e "${YELLOW}  ai is not on PATH. Installing this script to $install_path.${NC}"
        if ! doctor_install_file "$source" "$install_path" 0755; then
            return 1
        fi
        echo -e "${GREEN}  Installed ai -> $install_path${NC}"
        return 0
    fi

    if cmp -s "$source" "$path_ai"; then
        echo -e "${GREEN}  ai on PATH already matches this script ($path_ai).${NC}"
        return 0
    fi

    echo -e "${YELLOW}  ai on PATH differs from this script: $path_ai${NC}"
    echo -e "${YELLOW}  Updating $path_ai from $source.${NC}"
    if ! doctor_install_file "$source" "$path_ai" 0755; then
        return 1
    fi

    if cmp -s "$source" "$path_ai"; then
        echo -e "${GREEN}  Updated ai -> $path_ai${NC}"
    else
        echo -e "${RED}  Failed to verify updated ai at $path_ai.${NC}"
        return 1
    fi
}

doctor_check_npm_handoffs() {
    echo -e "${CYAN}==> Checking npm package handoffs...${NC}"

    if ! command -v npm >/dev/null 2>&1; then
        echo -e "${YELLOW}  npm not found; skipping npm package checks.${NC}"
        return 0
    fi

    cleanup_legacy_npm_package_prefixes \
        "Pi Coding Agent" \
        "@earendil-works/pi-coding-agent" \
        "pi" \
        "$(npm_install_prefix)" \
        "@mariozechner/pi-coding-agent"

    echo -e "${GREEN}  npm package handoffs checked.${NC}"
}

doctor_check_omx() {
    if ! ai_cli_enabled update omx; then
        return 0
    fi

    echo -e "${CYAN}==> Checking Oh My Codex...${NC}"

    if ! command -v omx >/dev/null 2>&1; then
        echo -e "${YELLOW}  ⚠ omx not found${NC}"
        if command -v npm >/dev/null 2>&1; then
            echo -e "${YELLOW}    Install with: npm install -g oh-my-codex${NC}"
        fi
        return 0
    fi

    local ver
    ver=$(omx --version 2>/dev/null | head -1 || true)
    if [[ -n "$ver" ]]; then
        echo -e "${GREEN}  ✓ Oh My Codex: $ver${NC}"
    else
        echo -e "${GREEN}  ✓ Oh My Codex: installed${NC}"
    fi

    if $VERBOSE; then
        omx doctor 2>&1 || {
            echo -e "${YELLOW}  ⚠ omx doctor reported issues${NC}"
        }
    else
        omx doctor >/dev/null 2>&1 || {
            echo -e "${YELLOW}  ⚠ omx doctor reported issues; run 'omx doctor' for details.${NC}"
        }
    fi
}

do_doctor() {
    local failed=false

    doctor_check_ai_cli_install || failed=true
    echo ""
    ensure_update_dependencies || failed=true
    echo ""
    doctor_check_npm_handoffs || failed=true
    echo ""
    doctor_check_omx || failed=true

    echo ""
    if $failed; then
        echo -e "${RED}Doctor found issues it could not fix.${NC}"
        return 1
    fi

    echo -e "${GREEN}Doctor checks complete.${NC}"
}

pi_vs_claude_code_dir() {
    printf '%s\n' "${AI_CLI_PI_VS_CLAUDE_CODE_DIR:-$(ai_cli_data_dir)/pi-vs-claude-code}"
}

read_git_head() {
    local repo_dir="$1"

    git -C "$repo_dir" rev-parse --short HEAD 2>/dev/null || true
}

check_pi_vs_claude_code() {
    echo -e "${CYAN}==> Checking Pi vs Claude Code...${NC}"

    local repo_url="https://github.com/disler/pi-vs-claude-code.git"
    local repo_dir
    repo_dir="$(pi_vs_claude_code_dir)"

    if ! ensure_command_dependency git git "Git"; then
        echo -e "${YELLOW}  Git is required to install this repo.${NC}"
        return
    fi

    if [[ -d "$repo_dir/.git" ]]; then
        local current
        current=$(read_git_head "$repo_dir")
        if $VERBOSE; then
            git -C "$repo_dir" pull --ff-only
        else
            git -C "$repo_dir" pull --ff-only >/dev/null 2>&1 || {
                echo -e "${YELLOW}  Update failed. Run with --verbose for git output.${NC}"
                return
            }
        fi

        local updated
        updated=$(read_git_head "$repo_dir")
        if [[ -n "$current" && "$current" == "$updated" ]]; then
            echo -e "${GREEN}  Repo already up to date (${updated})${NC}"
        else
            echo -e "${YELLOW}  Updated repo ${current:-unknown} -> ${updated:-unknown}${NC}"
        fi
    elif [[ -e "$repo_dir" ]]; then
        echo -e "${YELLOW}  $repo_dir exists but is not a git checkout. Set AI_CLI_PI_VS_CLAUDE_CODE_DIR to another path.${NC}"
        return
    else
        mkdir -p "$(dirname "$repo_dir")"
        echo -e "${YELLOW}  Not installed, cloning...${NC}"
        if $VERBOSE; then
            git clone "$repo_url" "$repo_dir"
        else
            git clone "$repo_url" "$repo_dir" >/dev/null 2>&1 || {
                echo -e "${YELLOW}  Clone failed. Run with --verbose for git output.${NC}"
                return
            }
        fi
        echo -e "${GREEN}  Cloned to $repo_dir${NC}"
    fi

    if ! ensure_bun_dependency; then
        echo -e "${YELLOW}  Bun is required for dependencies.${NC}"
        return
    fi

    if $VERBOSE; then
        bun install --cwd "$repo_dir"
    else
        bun install --cwd "$repo_dir" >/dev/null 2>&1 || {
            echo -e "${YELLOW}  Dependency install failed. Run with --verbose for bun output.${NC}"
            return
        }
    fi

    ensure_just_dependency || true
    if command -v just >/dev/null 2>&1; then
        echo -e "${GREEN}  Dependencies installed. Run recipes from $repo_dir with 'just'.${NC}"
    else
        echo -e "${YELLOW}  Dependencies installed. Install 'just' to use the bundled recipes in $repo_dir.${NC}"
    fi
}

check_antigravity() {
    echo -e "${CYAN}==> Checking Antigravity CLI...${NC}"
    local old_ver=""
    if command -v agy >/dev/null 2>&1; then
        old_ver=$(agy --version 2>/dev/null || true)
    else
        echo -e "${YELLOW}  Not installed, installing...${NC}"
    fi

    local installer_script
    if ! installer_script=$(curl -fsSL https://antigravity.google/cli/install.sh 2>/dev/null); then
        echo -e "${YELLOW}  Failed to download Antigravity installer${NC}"
        return
    fi

    if $VERBOSE; then
        echo "$installer_script" | bash
    else
        echo "$installer_script" | bash >/dev/null 2>&1
    fi

    if ! command -v agy >/dev/null 2>&1; then
        echo -e "${YELLOW}  Installation failed${NC}"
        return
    fi

    local new_ver
    new_ver=$(agy --version 2>/dev/null || true)
    if [[ -z "$old_ver" ]]; then
        echo -e "${GREEN}  Installed (${new_ver})${NC}"
    elif [[ "$old_ver" == "$new_ver" ]]; then
        echo -e "${GREEN}  Already up to date (${new_ver})${NC}"
    else
        echo -e "${YELLOW}  Updated ${old_ver} -> ${new_ver}${NC}"
    fi
}

check_claude() {
    echo -e "${CYAN}==> Checking Claude Code...${NC}"
    local old_ver=""
    if command -v claude >/dev/null 2>&1; then
        old_ver=$(claude --version 2>/dev/null || true)
    else
        echo -e "${YELLOW}  Not installed, installing...${NC}"
    fi

    if $VERBOSE; then
        curl -fsSL https://claude.ai/install.sh | bash
    else
        curl -fsSL https://claude.ai/install.sh | bash >/dev/null 2>&1
    fi

    if ! command -v claude >/dev/null 2>&1; then
        echo -e "${YELLOW}  Installation failed${NC}"
        return
    fi

    local new_ver
    new_ver=$(claude --version 2>/dev/null || true)
    if [[ -z "$old_ver" ]]; then
        echo -e "${GREEN}  Installed (${new_ver})${NC}"
    elif [[ "$old_ver" == "$new_ver" ]]; then
        echo -e "${GREEN}  Already up to date (${new_ver})${NC}"
    else
        echo -e "${YELLOW}  Updated ${old_ver} -> ${new_ver}${NC}"
    fi
}

check_gh_cli() {
    echo -e "${CYAN}==> Checking GitHub CLI...${NC}"
    local current
    current=$(gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
    if [[ -z "$current" ]]; then
        echo -e "${YELLOW}  Not installed${NC}"
        return
    fi

    # Detect package manager and upgrade
    if command -v apt-get &>/dev/null; then
        local output
        if $VERBOSE; then
            output=$(sudo apt-get update 2>&1 && sudo apt-get install --only-upgrade gh 2>&1 | tee /dev/stderr) || true
        else
            output=$(sudo apt-get update -qq 2>&1 && sudo apt-get install --only-upgrade -qq gh 2>&1) || true
        fi
        local new_ver
        new_ver=$(gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
        if [[ "$current" == "$new_ver" ]]; then
            echo -e "${GREEN}  Already up to date (${current})${NC}"
        else
            echo -e "${YELLOW}  Updated ${current} -> ${new_ver}${NC}"
        fi
    elif command -v dnf &>/dev/null; then
        local output
        if $VERBOSE; then
            sudo dnf install gh --repo gh-cli -y 2>&1 | tee /dev/stderr || true
        else
            sudo dnf install gh --repo gh-cli -y -q 2>&1 >/dev/null || true
        fi
        local new_ver
        new_ver=$(gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
        if [[ "$current" == "$new_ver" ]]; then
            echo -e "${GREEN}  Already up to date (${current})${NC}"
        else
            echo -e "${YELLOW}  Updated ${current} -> ${new_ver}${NC}"
        fi
    elif command -v pacman &>/dev/null; then
        local local_ver sync_ver
        local_ver=$(pacman -Qi github-cli 2>/dev/null | grep "^Version" | awk '{print $3}' | head -n 1 || true)
        sync_ver=$(pacman -Si github-cli 2>/dev/null | grep "^Version" | awk '{print $3}' | head -n 1 || true)

        # Only attempt install if sync version is different (newer) than local
        if [[ -n "$sync_ver" && "$local_ver" != "$sync_ver" ]]; then
            if $VERBOSE; then
                sudo pacman -Sy --noconfirm github-cli 2>&1 || true
            else
                sudo pacman -Sy --noconfirm github-cli 2>&1 >/dev/null || true
            fi
        fi
        local new_ver
        new_ver=$(gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
        if [[ "$current" == "$new_ver" ]]; then
            echo -e "${GREEN}  Already up to date (${current})${NC}"
        else
            echo -e "${YELLOW}  Updated ${current} -> ${new_ver}${NC}"
        fi
    elif command -v brew &>/dev/null; then
        if $VERBOSE; then
            brew upgrade gh 2>&1 || true
        else
            brew upgrade gh 2>&1 >/dev/null || true
        fi
        local new_ver
        new_ver=$(gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)
        if [[ "$current" == "$new_ver" ]]; then
            echo -e "${GREEN}  Already up to date (${current})${NC}"
        else
            echo -e "${YELLOW}  Updated ${current} -> ${new_ver}${NC}"
        fi
    else
        echo -e "${YELLOW}  Installed (${current}) — could not detect package manager to upgrade${NC}"
    fi
}

check_gh_copilot() {
    echo -e "${CYAN}==> Checking GitHub Copilot CLI...${NC}"
    if $VERBOSE; then
        gh copilot update 2>&1 | tee /tmp/ai-copilot-update.log || true
        local output
        output=$(cat /tmp/ai-copilot-update.log)
    else
        local output
        output=$(gh copilot update 2>&1 || true)
    fi
    if echo "$output" | grep -q "No update needed"; then
        local ver
        ver=$(echo "$output" | sed -n 's/.*current version is \([^, ]*\).*/\1/p' || true)
        echo -e "${GREEN}  Already up to date (${ver})${NC}"
    elif echo "$output" | grep -qi "updated\|updating"; then
        echo -e "${YELLOW}  Updated successfully${NC}"
    else
        echo -e "${GREEN}  Already up to date${NC}"
    fi
}

install_hermes() {
    local install_dir="${1:-}"
    local install_url="https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh"
    local -a env_cmd=(env "CI=${CI:-true}")

    if [[ -n "$install_dir" ]]; then
        env_cmd+=("HERMES_INSTALL_DIR=$install_dir")
    fi

    if $VERBOSE; then
        curl -fsSL "$install_url" | "${env_cmd[@]}" bash -s -- --skip-setup
    else
        curl -fsSL "$install_url" 2>/dev/null | "${env_cmd[@]}" bash -s -- --skip-setup >/dev/null 2>&1
    fi
}

read_hermes_version() {
    local output

    output=$(hermes --version 2>/dev/null || hermes version 2>/dev/null || true)
    printf '%s\n' "$output" | head -n 1 | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 || true
}

read_hermes_project_dir() {
    local output

    output=$(hermes --version 2>/dev/null || hermes version 2>/dev/null || true)
    printf '%s\n' "$output" | sed -n 's/^Project:[[:space:]]*//p' | head -n 1
}

git_worktree_dirty() {
    local repo_dir="$1"
    [[ -n "$(git -C "$repo_dir" status --porcelain 2>/dev/null)" ]]
}

sync_hermes_with_upstream() {
    local repo_dir="$1"
    local branch upstream_url before after
    local upstream_ahead update_mode

    HERMES_UPSTREAM_SYNC_FAILED=false
    [[ -n "$repo_dir" && -d "$repo_dir/.git" ]] || return 1

    branch=$(git -C "$repo_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || true)
    [[ "$branch" == "main" ]] || return 1

    upstream_url=$(git -C "$repo_dir" remote get-url upstream 2>/dev/null || true)
    if [[ -z "$upstream_url" ]]; then
        git -C "$repo_dir" remote add upstream https://github.com/NousResearch/hermes-agent.git 2>/dev/null || return 1
    fi

    if $VERBOSE; then
        git -C "$repo_dir" fetch upstream || return 1
    else
        git -C "$repo_dir" fetch upstream >/dev/null 2>&1 || return 1
    fi

    upstream_ahead=$(git -C "$repo_dir" rev-list --count HEAD..upstream/main 2>/dev/null || printf '0')
    [[ "$upstream_ahead" =~ ^[0-9]+$ && "$upstream_ahead" -gt 0 ]] || return 1

    if git_worktree_dirty "$repo_dir"; then
        HERMES_UPSTREAM_SYNC_FAILED=true
        echo -e "${YELLOW}  Hermes checkout has local changes; leaving it untouched.${NC}"
        return 1
    fi

    if git -C "$repo_dir" merge-base --is-ancestor HEAD upstream/main >/dev/null 2>&1; then
        update_mode="ff"
    else
        update_mode="merge"
        echo -e "${YELLOW}  Hermes fork has local commits; merging upstream/main to preserve them.${NC}"
    fi

    if [[ "$update_mode" == "merge" ]] && ! git -C "$repo_dir" merge-tree "$(git -C "$repo_dir" merge-base HEAD upstream/main)" HEAD upstream/main >/dev/null 2>&1; then
        return 1
    fi

    before=$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null || true)

    if [[ "$update_mode" == "ff" ]]; then
        if $VERBOSE; then
            git -C "$repo_dir" pull --ff-only upstream main || return 1
        else
            git -C "$repo_dir" pull --ff-only upstream main >/dev/null 2>&1 || return 1
        fi
    else
        if $VERBOSE; then
            git -C "$repo_dir" -c user.name=ai-cli -c user.email=ai-cli@localhost merge --no-edit upstream/main || {
                git -C "$repo_dir" merge --abort >/dev/null 2>&1 || true
                HERMES_UPSTREAM_SYNC_FAILED=true
                echo -e "${YELLOW}  Could not merge upstream/main into the Hermes fork automatically.${NC}"
                return 1
            }
        else
            git -C "$repo_dir" -c user.name=ai-cli -c user.email=ai-cli@localhost merge --no-edit upstream/main >/dev/null 2>&1 || {
                git -C "$repo_dir" merge --abort >/dev/null 2>&1 || true
                HERMES_UPSTREAM_SYNC_FAILED=true
                echo -e "${YELLOW}  Could not merge upstream/main into the Hermes fork automatically.${NC}"
                return 1
            }
        fi
    fi

    after=$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null || true)
    [[ -n "$before" && -n "$after" && "$before" != "$after" ]]
}

check_hermes() {
    echo -e "${CYAN}==> Checking Hermes Agent...${NC}"
    ensure_command_dependency curl curl "curl" || return
    ensure_command_dependency git git "Git" || return

    if ! command -v hermes >/dev/null 2>&1; then
        echo -e "${YELLOW}  Not installed, installing...${NC}"
        if ! install_hermes; then
            echo -e "${YELLOW}  Installation failed${NC}"
            return
        fi

        prepend_path_dir "$HOME/.local/bin"
        prepend_path_dir "/usr/local/bin"
        if [[ -n "${PREFIX:-}" ]]; then
            prepend_path_dir "$PREFIX/bin"
        fi

        if ! command -v hermes >/dev/null 2>&1; then
            echo -e "${YELLOW}  Installed, but hermes is not on PATH yet. Restart your shell and try again.${NC}"
            return
        fi

        local installed
        installed=$(read_hermes_version)
        if [[ -n "$installed" ]]; then
            echo -e "${GREEN}  Installed (${installed})${NC}"
        else
            echo -e "${GREEN}  Installed${NC}"
        fi
        return
    fi

    local current start_ver new_ver iteration updated=false
    local project_dir upstream_synced=false

    start_ver=$(read_hermes_version)
    project_dir=$(read_hermes_project_dir)
    if sync_hermes_with_upstream "$project_dir"; then
        upstream_synced=true
        install_hermes "$project_dir" || true
    elif [[ "${HERMES_UPSTREAM_SYNC_FAILED:-false}" == "true" ]]; then
        echo -e "${YELLOW}  Switching Hermes launcher to the official checkout so latest can install without overwriting fork commits.${NC}"
        install_hermes || true
    fi

    current=$(read_hermes_version)

    # Hermes updates reinstall Node dependencies whose postinstall hooks may
    # write directly to /dev/tty, bypassing stdout/stderr redirection.  CI=true
    # keeps those cosmetic install demos quiet without disabling required
    # install scripts.
    for iteration in {1..8}; do
        if $VERBOSE; then
            CI="${CI:-true}" hermes update
        else
            CI="${CI:-true}" hermes update >/dev/null 2>&1
        fi

        new_ver=$(read_hermes_version)
        if [[ -z "$new_ver" ]]; then
            break
        fi

        if [[ -n "$current" && "$new_ver" == "$current" ]]; then
            break
        fi

        updated=true
        current="$new_ver"
    done

    if $updated && [[ -n "$current" ]]; then
        echo -e "${YELLOW}  Updated ${start_ver:-unknown} -> ${current}${NC}"
    elif [[ -n "$start_ver" && -n "$current" && "$start_ver" != "$current" ]]; then
        echo -e "${YELLOW}  Updated ${start_ver} -> ${current}${NC}"
    elif $upstream_synced && [[ -n "$current" ]]; then
        echo -e "${YELLOW}  Updated from upstream (${current})${NC}"
    elif [[ -n "$current" ]]; then
        echo -e "${GREEN}  Already up to date (${current})${NC}"
    else
        echo -e "${GREEN}  Update check complete${NC}"
    fi
}

check_omx() {
    echo -e "${CYAN}==> Checking Oh My Codex...${NC}"
    check_npm_package "Oh My Codex" "oh-my-codex" "omx"

    if command -v omx >/dev/null 2>&1; then
        if $VERBOSE; then
            omx doctor 2>&1 || true
        else
            omx doctor >/dev/null 2>&1 || {
                echo -e "${YELLOW}  omx doctor reported issues; run 'omx doctor' for details.${NC}"
            }
        fi
    fi
}

render_usage_bar() {
    python3 - "$1" <<'PY'
import sys

try:
    percent = float(sys.argv[1])
except Exception:
    percent = 0.0

segments = 20
ratio = max(0.0, min(1.0, percent / 100.0))
filled = min(segments, max(0, int(round(ratio * segments))))
print("[" + "#" * filled + "-" * (segments - filled) + "]")
PY
}

print_usage_row() {
    local label="$1"
    local percent="$2"
    local reset_at="$3"
    local bar

    bar=$(render_usage_bar "$percent")
    printf '  %-24s %s %6.1f%% left' "$label" "$bar" "$percent"
    if [[ -n "$reset_at" ]]; then
        printf '  resets %s' "$reset_at"
    fi
    printf '\n'
}

print_usage_rows() {
    local output="$1"
    local empty_message="$2"

    if [[ -z "$output" ]]; then
        echo -e "${YELLOW}  ${empty_message}${NC}"
        return
    fi

    while IFS=$'\t' read -r label percent reset_at; do
        [[ -n "$label" ]] || continue
        if [[ "$label" == "__BLANK__" ]]; then
            printf '\n'
            continue
        fi
        if [[ "$label" == "__TEXT__" ]]; then
            echo -e "${YELLOW}  ${percent}${NC}"
            continue
        fi
        if [[ "$reset_at" == "__EMPTY__" ]]; then
            reset_at=""
        fi
        [[ -n "$percent" ]] || continue
        print_usage_row "$label" "$percent" "$reset_at"
    done <<< "$output"
}

usage_claude() {
    echo -e "${CYAN}==> Claude Code...${NC}"
    local output

    if ! output=$(python3 <<'PY' 2>/dev/null
import json
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timedelta
from email.utils import parsedate_to_datetime
from pathlib import Path


REFRESH_URL = "https://platform.claude.com/v1/oauth/token"
CLIENT_ID = "9d1c250a-e61b-44d9-88ed-5944d1962f5e"
SCOPES = "user:profile user:inference user:sessions:claude_code user:mcp_servers user:file_upload"
CREDS_PATH = Path.home() / ".claude" / ".credentials.json"
STATUS_URL = "https://status.claude.com/api/v2/components.json"


def fmt_reset(value):
    if not value:
        return ""
    try:
        value = value.replace("Z", "+00:00")
        reset_at = datetime.fromisoformat(value).astimezone()
        delta_seconds = max(0, int((reset_at - datetime.now(reset_at.tzinfo)).total_seconds()))
        days = delta_seconds // 86400
        hours = (delta_seconds % 86400) // 3600
        minutes = (delta_seconds % 3600) // 60
        if days:
            delta_text = f"{days}d {hours}h"
        elif hours:
            delta_text = f"{hours}h {minutes}m"
        else:
            delta_text = f"{minutes}m"
        return f"{reset_at.strftime('%Y-%m-%d %H:%M')} ({delta_text})"
    except Exception:
        return value


def cache_path():
    return Path.home() / ".claude" / ".usage_cache.json"


def parse_iso_timestamp(value):
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone()
    except Exception:
        return None


def fmt_cached_at(value):
    timestamp = parse_iso_timestamp(value)
    if not timestamp:
        return value or "unknown time"

    age_seconds = max(0, int((datetime.now(timestamp.tzinfo) - timestamp).total_seconds()))
    days = age_seconds // 86400
    hours = (age_seconds % 86400) // 3600
    minutes = (age_seconds % 3600) // 60

    if days:
        age = f"{days}d {hours}h ago"
    elif hours:
        age = f"{hours}h {minutes}m ago"
    else:
        age = f"{minutes}m ago"

    return f"{timestamp.strftime('%Y-%m-%d %H:%M')} ({age})"


def retry_after_to_iso(value):
    if not value:
        return None

    try:
        seconds = max(0, int(value))
        return (datetime.now().astimezone() + timedelta(seconds=seconds)).isoformat()
    except Exception:
        pass

    try:
        return parsedate_to_datetime(value).astimezone().isoformat()
    except Exception:
        return None


def is_rate_limit_active(value):
    deadline = parse_iso_timestamp(value)
    if not deadline:
        return False
    return deadline > datetime.now(deadline.tzinfo)


def load_cached_payload():
    path = cache_path()
    if not path.exists():
        return None, None, None

    try:
        cached = json.loads(path.read_text())
        payload = cached.get("payload")
        cached_at = cached.get("cached_at")
        rate_limited_until = cached.get("rate_limited_until")
        if isinstance(payload, dict):
            return payload, cached_at, rate_limited_until
        return None, cached_at, rate_limited_until
    except Exception:
        pass

    return None, None, None


def save_cached_payload(payload):
    try:
        path = cache_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps({"cached_at": datetime.now().astimezone().isoformat(), "payload": payload})
        )
    except Exception:
        pass


def save_rate_limit_until(rate_limited_until):
    try:
        path = cache_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        cached = {}
        if path.exists():
            try:
                cached = json.loads(path.read_text())
            except Exception:
                cached = {}
        if rate_limited_until:
            cached["rate_limited_until"] = rate_limited_until
        else:
            cached.pop("rate_limited_until", None)
        path.write_text(json.dumps(cached))
    except Exception:
        pass


def refresh_oauth_token(creds):
    """Refresh the OAuth token and persist new credentials.
    Returns (new_token, None) on success, (None, message) on actionable failure,
    or (None, None) on transient/unknown failure.
    """
    oauth = creds.get("claudeAiOauth", {})
    rt = oauth.get("refreshToken")
    if not rt:
        return None, "Session expired \u2014 run `claude auth login` to re-login"
    body = json.dumps({
        "grant_type": "refresh_token",
        "refresh_token": rt,
        "client_id": CLIENT_ID,
        "scope": SCOPES,
    }).encode("utf-8")
    req = urllib.request.Request(
        REFRESH_URL,
        data=body,
        headers={
            "Content-Type": "application/json",
            "User-Agent": "claude-code",
            "Accept": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code in (400, 401, 403):
            try:
                err = json.loads(exc.read().decode("utf-8"))
            except Exception:
                err = {}
            if err.get("error") == "invalid_grant":
                return None, "Session expired \u2014 run `claude auth login` to re-login"
            return None, "Token refresh failed \u2014 run `claude auth login` to re-login"
        return None, None  # transient error, let caller retry
    except Exception:
        return None, None  # network error, let caller retry
    new_token = data.get("access_token")
    if not new_token:
        return None, None
    oauth["accessToken"] = new_token
    oauth["refreshToken"] = data.get("refresh_token", rt)
    oauth["expiresAt"] = int(time.time() * 1000) + data.get("expires_in", 3600) * 1000
    creds["claudeAiOauth"] = oauth
    try:
        CREDS_PATH.write_text(json.dumps(creds))
    except Exception:
        pass
    return new_token, None

def get_claude_status():
    """Check status.claude.com for Claude Code component status."""
    try:
        req = urllib.request.Request(
            STATUS_URL,
            headers={"Accept": "application/json", "User-Agent": "ai-cli"},
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        issues = []
        for comp in data.get("components", []):
            name = comp.get("name", "")
            if name in ("Claude Code", "Claude API (api.anthropic.com)"):
                status = comp.get("status", "unknown")
                if status != "operational":
                    label = status.replace("_", " ").title()
                    issues.append(f"{name}: {label}")
        return "; ".join(issues) if issues else None
    except Exception:
        pass
    return None


def make_usage_request(token):
    return urllib.request.Request(
        "https://api.anthropic.com/api/oauth/usage",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/json",
            "anthropic-version": "2023-06-01",
            "anthropic-beta": "oauth-2025-04-20",
            "User-Agent": "claude-code",
        },
    )


def rows_from_payload(payload):
    rows = []
    for key, label in (
        ("five_hour", "5h limit"),
        ("seven_day", "7d limit"),
        ("seven_day_sonnet", "7d sonnet"),
        ("seven_day_opus", "7d opus"),
    ):
        item = payload.get(key) or {}
        utilization = item.get("utilization")
        if utilization is None:
            continue
        rows.append((label, max(0.0, 100.0 - float(utilization)), fmt_reset(item.get("resets_at"))))
    extra = payload.get("extra_usage") or {}
    if extra.get("is_enabled") and extra.get("utilization") is not None:
        rows.append(("extra usage", max(0.0, 100.0 - float(extra["utilization"])), ""))
    return rows


# -- main --
if not CREDS_PATH.exists():
    sys.exit(1)
creds = json.loads(CREDS_PATH.read_text())
oauth = creds.get("claudeAiOauth", {})
token = oauth.get("accessToken")
if not token:
    sys.exit(1)
# Proactively refresh if token expired or within 5 minutes of expiry
expires_at = oauth.get("expiresAt", 0)
token_refreshed = False
refresh_msg = None
if time.time() * 1000 + 5 * 60 * 1000 >= expires_at:
    new_token, refresh_msg = refresh_oauth_token(creds)
    if new_token:
        token = new_token
        token_refreshed = True
        refresh_msg = None

cached_payload, cached_at, rate_limited_until = load_cached_payload()
payload = None
if refresh_msg:
    payload = cached_payload
else:
    if cached_payload is not None and is_rate_limit_active(rate_limited_until):
        payload = cached_payload
    else:
        for attempt in range(3):
            try:
                with urllib.request.urlopen(make_usage_request(token), timeout=30) as response:
                    payload = json.loads(response.read().decode("utf-8"))
                save_cached_payload(payload)
                rate_limited_until = None
                cached_at = None
                break
            except urllib.error.HTTPError as exc:
                if exc.code == 401 and not token_refreshed:
                    token_refreshed = True
                    new_token, msg = refresh_oauth_token(creds)
                    if new_token:
                        token = new_token
                        continue
                    # Refresh failed -- fall back to cache
                    refresh_msg = msg
                    payload, cached_at, rate_limited_until = load_cached_payload()
                    if payload is None and not refresh_msg:
                        status_msg = get_claude_status()
                        if status_msg:
                            refresh_msg = f"⚠ {status_msg}"
                        else:
                            refresh_msg = "Usage unavailable"
                    break
                if exc.code != 429:
                    raise
                rate_limited_until = retry_after_to_iso(exc.headers.get("Retry-After"))
                save_rate_limit_until(rate_limited_until)
                payload, cached_at, rate_limited_until = load_cached_payload()
                if payload is None:
                    if rate_limited_until:
                        refresh_msg = f"Usage unavailable (Claude rate limited until {fmt_reset(rate_limited_until)})"
                    else:
                        refresh_msg = "Usage unavailable (Claude rate limited)"
                break
            except Exception:
                payload, cached_at, rate_limited_until = load_cached_payload()
                if payload is None:
                    status_msg = get_claude_status()
                    if status_msg:
                        refresh_msg = f"⚠ {status_msg}"
                    else:
                        refresh_msg = "Usage unavailable"
                break

# Output results
if payload is None and refresh_msg:
    # No cached data either -- just print the message and exit successfully
    print(f"__TEXT__\t{refresh_msg}\t")
    sys.exit(0)
elif payload is None:
    sys.exit(1)
rows = rows_from_payload(payload)
if not rows:
    sys.exit(1)
# Print the actionable message first (e.g. "Session expired -- run claude auth login")
if refresh_msg:
    print(f"__TEXT__	{refresh_msg}	")
for label, percent, reset_at in rows:
    print(f"{label}	{percent:.1f}	{reset_at or '__EMPTY__'}")
if cached_at:
    cache_note = f"Showing cached usage from {fmt_cached_at(cached_at)}"
    if is_rate_limit_active(rate_limited_until):
        cache_note += f"; Claude API rate limited until {fmt_reset(rate_limited_until)}"
    print(f"__TEXT__	{cache_note}	__EMPTY__")
# Always surface status page degradation if present
status_msg = get_claude_status()
if status_msg:
    print(f"__TEXT__\t\u26a0 {status_msg}\t")
PY
    ); then
        echo -e "${YELLOW}  Usage unavailable${NC}"
        return
    fi
    print_usage_rows "$output" "Usage unavailable"
}

usage_codex() {
    echo -e "${CYAN}==> Codex CLI...${NC}"
    local output

    if ! output=$(python3 <<'PY' 2>/dev/null
import json
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


CLIENT_ID = "app_EMoamEEZ73f0CkXaXp7hrann"
TOKEN_URL = "https://auth.openai.com/oauth/token"
USAGE_URL = "https://chatgpt.com/backend-api/wham/usage"
AUTH_PATH = Path.home() / ".codex" / "auth.json"


def fmt_reset(value):
    if not value:
        return ""
    try:
        reset_at = datetime.fromtimestamp(int(value)).astimezone()
        delta_seconds = max(0, int((reset_at - datetime.now(reset_at.tzinfo)).total_seconds()))
        days = delta_seconds // 86400
        hours = (delta_seconds % 86400) // 3600
        return f"{reset_at.strftime('%Y-%m-%d %H:%M')} ({days}d {hours}h)"
    except Exception:
        return str(value)


def refresh_codex_token(data):
    """Refresh the access token and persist new credentials.
    Returns (new_token, None) on success, (None, message) on actionable failure,
    or (None, None) on transient/unknown failure.
    """
    tokens = data.get("tokens") or {}
    rt = tokens.get("refresh_token")
    if not rt:
        return None, "Session expired \u2014 run `codex login` to re-login"
    body = urllib.parse.urlencode({
        "grant_type": "refresh_token",
        "refresh_token": rt,
        "client_id": CLIENT_ID,
    }).encode("utf-8")
    req = urllib.request.Request(
        TOKEN_URL,
        data=body,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code in (400, 401, 403):
            try:
                err = json.loads(exc.read().decode("utf-8"))
            except Exception:
                err = {}
            err_obj = err.get("error") or err
            code = err_obj.get("code") if isinstance(err_obj, dict) else None
            if code == "invalid_grant":
                return None, "Session expired \u2014 run `codex login` to re-login"
            return None, "Token refresh failed \u2014 run `codex login` to re-login"
        return None, None
    except Exception:
        return None, None
    new_token = result.get("access_token")
    if not new_token:
        return None, None
    tokens["access_token"] = new_token
    if result.get("refresh_token"):
        tokens["refresh_token"] = result["refresh_token"]
    data["tokens"] = tokens
    data["last_refresh"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        AUTH_PATH.write_text(json.dumps(data))
    except Exception:
        pass
    return new_token, None


def make_usage_request(token, account_id):
    return urllib.request.Request(
        USAGE_URL,
        headers={
            "Authorization": f"Bearer {token}",
            "chatgpt-account-id": account_id,
            "User-Agent": "codex-cli",
        },
    )


if not AUTH_PATH.exists():
    sys.exit(1)

data = json.loads(AUTH_PATH.read_text())
tokens = data.get("tokens") or {}
token = tokens.get("access_token")
account_id = tokens.get("account_id")
if not token or not account_id:
    sys.exit(1)

refresh_msg = None
payload = None
token_refreshed = False

try:
    with urllib.request.urlopen(make_usage_request(token, account_id), timeout=30) as response:
        payload = json.loads(response.read().decode("utf-8"))
except urllib.error.HTTPError as exc:
    if exc.code == 401 and not token_refreshed:
        token_refreshed = True
        new_token, msg = refresh_codex_token(data)
        if new_token:
            token = new_token
            try:
                with urllib.request.urlopen(make_usage_request(token, account_id), timeout=30) as response:
                    payload = json.loads(response.read().decode("utf-8"))
            except Exception:
                refresh_msg = "Usage unavailable"
        else:
            refresh_msg = msg
    else:
        refresh_msg = "Usage unavailable"
except Exception:
    refresh_msg = "Usage unavailable"

if payload is None and refresh_msg:
    print(f"__TEXT__\t{refresh_msg}\t")
    sys.exit(0)
elif payload is None:
    sys.exit(1)
rows = []
rate_limit = payload.get("rate_limit") or {}
for key, label in (("primary_window", "5h limit"), ("secondary_window", "7d limit")):
    window = rate_limit.get(key) or {}
    used = window.get("used_percent")
    if used is None:
        continue
    rows.append((label, max(0.0, 100.0 - float(used)), fmt_reset(window.get("reset_at"))))

if not rows:
    sys.exit(1)

for label, percent, reset_at in rows:
    print(f"{label}\t{percent:.1f}\t{reset_at}")
PY
    ); then
        echo -e "${YELLOW}  Usage unavailable${NC}"
        return
    fi

    print_usage_rows "$output" "Usage unavailable"
}

usage_antigravity() {
    echo -e "${CYAN}==> Antigravity CLI...${NC}"
    local output

    if ! command -v agy >/dev/null 2>&1; then
        echo -e "${YELLOW}  Usage unavailable (Antigravity CLI not installed)${NC}"
        return
    fi

    if ! output=$(python3 <<'PY' 2>/dev/null
import os
import re
import subprocess
import sys
import time


def print_text(message):
    print(f"__TEXT__\t{message}\t__EMPTY__")


def capture_usage_text():
    if os.environ.get("AI_CLI_ANTIGRAVITY_USAGE_TEXT"):
        return os.environ["AI_CLI_ANTIGRAVITY_USAGE_TEXT"]
    if os.environ.get("AI_CLI_ANTIGRAVITY_USAGE_FILE"):
        with open(os.environ["AI_CLI_ANTIGRAVITY_USAGE_FILE"], encoding="utf-8", errors="ignore") as handle:
            return handle.read()

    session = f"ai_cli_agy_usage_{os.getpid()}"
    prompt_timeout = float(os.environ.get("AI_CLI_ANTIGRAVITY_PROMPT_TIMEOUT", "8"))
    usage_timeout = float(os.environ.get("AI_CLI_ANTIGRAVITY_USAGE_TIMEOUT", "10"))
    poll_interval = float(os.environ.get("AI_CLI_ANTIGRAVITY_POLL_INTERVAL", "0.25"))

    def capture_pane():
        captured = subprocess.run(
            ["tmux", "capture-pane", "-p", "-t", session, "-S", "-300"],
            capture_output=True,
            text=True,
            timeout=10,
            check=True,
        )
        return captured.stdout

    def prompt_ready(text):
        return any(line.strip() == ">" for line in text.splitlines())

    def usage_ready(text):
        return "Model Quota" in text and ("Refreshes in" in text or "Quota available" in text)

    try:
        subprocess.run(
            ["tmux", "new-session", "-d", "-s", session, "-x", "140", "-y", "60", "agy --dangerously-skip-permissions"],
            capture_output=True,
            text=True,
            timeout=10,
            check=True,
        )

        deadline = time.monotonic() + prompt_timeout
        pane = ""
        while time.monotonic() < deadline:
            pane = capture_pane()
            if prompt_ready(pane):
                break
            time.sleep(poll_interval)
        else:
            return pane

        subprocess.run(["tmux", "send-keys", "-t", session, "/usage", "Enter"], timeout=10, check=True)

        deadline = time.monotonic() + usage_timeout
        while time.monotonic() < deadline:
            pane = capture_pane()
            if usage_ready(pane):
                return pane
            time.sleep(poll_interval)
        return capture_pane()
    finally:
        try:
            subprocess.run(["tmux", "kill-session", "-t", session], capture_output=True, timeout=5)
        except Exception:
            pass


def clean_line(line):
    line = re.sub(r"\x1b\[[0-9;?]*[A-Za-z]", "", line)
    return line.strip()


def parse_usage(text):
    lines = [clean_line(line) for line in text.splitlines()]
    rows = []
    seen = set()
    for idx, line in enumerate(lines):
        if not line or line in seen:
            continue
        if line.startswith((">", "└", "↑/", "esc ", "(", "Antigravity CLI")):
            continue
        if "%" in line or line in ("Model Quota", "Quota available"):
            continue
        if not re.match(r"^(Gemini|Claude|GPT-)", line):
            continue
        percent = None
        reset_at = "__EMPTY__"
        for look_ahead in lines[idx + 1 : idx + 5]:
            pct_match = re.search(r"([0-9]+(?:\.[0-9]+)?)%", look_ahead)
            if pct_match:
                percent = float(pct_match.group(1))
                continue
            refresh_match = re.search(r"Refreshes in ([A-Za-z0-9 ]+)", look_ahead)
            if refresh_match:
                reset_at = f"in {refresh_match.group(1).strip()}"
                break
            if look_ahead == "Quota available":
                reset_at = "__EMPTY__"
                break
        if percent is None:
            continue
        rows.append((line, percent, reset_at))
        seen.add(line)
    return rows


try:
    usage_text = capture_usage_text()
except FileNotFoundError:
    print_text("Usage unavailable (tmux is required to read Antigravity /usage)")
    sys.exit(0)
except subprocess.CalledProcessError:
    print_text("Usage unavailable (Antigravity /usage capture failed)")
    sys.exit(0)
except Exception as exc:
    print_text(f"Usage unavailable (Antigravity /usage capture failed: {exc.__class__.__name__})")
    sys.exit(0)

rows = parse_usage(usage_text)
if not rows:
    if "You are not logged into Antigravity" in usage_text:
        print_text("Usage unavailable (not logged into Antigravity)")
        sys.exit(0)
    print_text("Usage unavailable (Antigravity /usage returned no quota rows)")
    sys.exit(0)

for label, percent, reset_at in rows:
    print(f"{label}\t{percent:.1f}\t{reset_at}")
PY
    ); then
        echo -e "${YELLOW}  Usage unavailable${NC}"
        return
    fi

    print_usage_rows "$output" "Usage unavailable"
}

usage_copilot() {
    echo -e "${CYAN}==> GitHub Copilot CLI...${NC}"
    local output payload

    if ! payload=$(gh api /copilot_internal/user 2>/dev/null); then
        echo -e "${YELLOW}  Usage unavailable${NC}"
        return
    fi

    if ! output=$(python3 - "$payload" <<'PY' 2>/dev/null
import json
import sys
from datetime import datetime


def fmt_reset(value):
    if not value:
        return ""
    try:
        value = value.replace("Z", "+00:00")
        reset_at = datetime.fromisoformat(value).astimezone()
        delta_seconds = max(0, int((reset_at - datetime.now(reset_at.tzinfo)).total_seconds()))
        days = delta_seconds // 86400
        hours = (delta_seconds % 86400) // 3600
        minutes = (delta_seconds % 3600) // 60
        if days:
            delta_text = f"{days}d {hours}h"
        elif hours:
            delta_text = f"{hours}h {minutes}m"
        else:
            delta_text = f"{minutes}m"
        return f"{reset_at.strftime('%Y-%m-%d %H:%M')} ({delta_text})"
    except Exception:
        return value


payload = json.loads(sys.argv[1])

rows = []
for key, value in sorted((payload.get("quota_snapshots") or {}).items()):
    if not value:
        continue

    entitlement = value.get("entitlement") or value.get("entitlementRequests") or 0
    if key != "premium_interactions" and entitlement <= 0:
        continue

    percent = value.get("percent_remaining")
    if percent is None:
        percent = value.get("remainingPercentage")
        if percent is not None and float(percent) <= 1.0:
            percent = float(percent) * 100.0

    if percent is None:
        continue

    timestamp = value.get("resetDate") or payload.get("quota_reset_date_utc") or payload.get("quota_reset_date")
    rows.append((key.replace("_", " "), float(percent), fmt_reset(timestamp)))

if not rows:
    sys.exit(1)

for label, percent, reset_at in rows:
    print(f"{label}\t{percent:.1f}\t{reset_at}")
PY
    ); then
        echo -e "${YELLOW}  Usage unavailable${NC}"
        return
    fi

    print_usage_rows "$output" "Usage unavailable"
}

do_usage() {
    usage_ran=false
    run_selected_usage claude usage_claude
    run_selected_usage codex usage_codex
    run_selected_usage antigravity usage_antigravity
    run_selected_usage copilot usage_copilot

    if ! $usage_ran; then
        echo -e "${YELLOW}No usage providers selected. Run 'ai setup' to choose providers.${NC}"
    else
        echo ""
        echo -e "${GREEN}Usage check complete.${NC}"
    fi
}

run_selected_usage() {
    local tool="$1"
    shift

    if ai_cli_enabled usage "$tool"; then
        if $usage_ran; then
            echo ""
        fi
        "$@"
        usage_ran=true
    fi
}

do_update() {
    local dependency_ok=true
    update_ran=false

    ensure_update_dependencies || dependency_ok=false
    echo ""

    run_selected_update claude check_claude
    run_selected_update gh_cli check_gh_cli
    run_selected_update copilot check_gh_copilot
    run_selected_update antigravity check_antigravity
    run_selected_update codex check_npm_package "Codex CLI" "@openai/codex" "codex"
    run_selected_update pi check_npm_package "Pi Coding Agent" "@earendil-works/pi-coding-agent" "pi" "@mariozechner/pi-coding-agent"
    run_selected_update pi_vs_claude_code check_pi_vs_claude_code
    run_selected_update hermes check_hermes
    run_selected_update omx check_omx

    if ! $update_ran; then
        echo -e "${YELLOW}No update tools selected. Run 'ai setup' to choose tools.${NC}"
    else
        echo ""
        if $dependency_ok; then
            echo -e "${GREEN}All selected AI tools checked.${NC}"
        else
            echo -e "${YELLOW}All selected AI tools checked, but some dependencies could not be installed.${NC}"
            return 1
        fi
    fi
}

run_selected_update() {
    local tool="$1"
    shift

    if ai_cli_enabled update "$tool"; then
        if $update_ran; then
            echo ""
        fi
        "$@"
        update_ran=true
    fi
}

run_claude() {
    local uid
    uid="${EUID:-$(id -u)}"

    if [[ "$uid" -eq 0 ]]; then
        exec env IS_SANDBOX=1 CLAUDE_CODE_BUBBLEWRAP=1 claude --dangerously-skip-permissions "$@"
    fi

    exec claude --dangerously-skip-permissions "$@"
}

tool="${1:-}"
shift 2>/dev/null || true

case "$tool" in
    claude)  run_claude "$@" ;;
    codex)   exec codex --yolo "$@" ;;
    antigravity|agy) exec agy --dangerously-skip-permissions "$@" ;;
    copilot) exec gh copilot --yolo "$@" ;;
    pi)      exec pi "$@" ;;
    hermes)  exec hermes --yolo "$@" ;;
    update)  do_update ;;
    doctor)  do_doctor ;;
    usage)   do_usage ;;
    setup)   do_setup ;;
    *)
        echo "Usage: ai <tool> [extra args]"
        echo "  ai claude   -> claude --dangerously-skip-permissions"
        echo "  ai codex    -> codex --yolo"
        echo "  ai antigravity -> agy --dangerously-skip-permissions"
        echo "  ai copilot  -> gh copilot --yolo"
        echo "  ai pi       -> pi"
        echo "  ai hermes   -> hermes --yolo"
        echo "  ai update   -> update all AI tools"
        echo "  ai doctor   -> diagnose and repair ai-cli install issues"
        echo "  ai usage    -> show remaining usage by provider"
        echo "  ai setup    -> choose tools for update and usage checks"
        echo ""
        echo "Options:"
        echo "  ai update --verbose  -> show full output from all tools"
        ;;
esac
